modLoader = "javafml"
loaderVersion = "[1,)"

license = "LGPL-3.0-or-later"
[[mods]]
modId = "disabletrial"
version = "0.1.2.1"
displayName = "Disable Trial Spawners"
authors = "WozuXbox"
description = '''
Enables players to disable trial spawners
'''
logoFile = "pack.png"
[[dependencies.disabletrial]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.0,1.21.2)"
ordering = "NONE"
side = "BOTH"